extends Node
var good = {
	"AFFECTIONATE": ["affectionate", "compassionate", "friendly", "loving", "open hearted", "sympathetic", "tender","warm"],
	"ENGAGED": ["engaged", "absorbed", "alert", "curious", "engrossed", "enchanted", "entranced", "fascinated","interested", "intrigued", "involved", "spellbound", "stimulated"],
	"HOPEFUL": ["hopeful", "expectant", "encouraged", "optimistic"],
	"CONFIDENT": ["confident", "empowered", "open", "proud", "safe", "secure"],
	"EXCITED": ["excited", "amazed", "animated", "ardent", "aroused", "astonished", "dazzled", "eager", "energetic","enthusiastic", "giddy", "invigorated", "lively", "passionate", "surprised", "vibrant"],
	"GRATEFUL": ["grateful", "appreciative", "moved", "thankful", "touched"],
	"INSPIRED": ["inspired", "amazed", "awed", "wonder"],
	"JOYFUL": ["joyful", "amused", "delighted", "glad", "happy", "jubilant", "pleased", "tickled"],
	"EXHILARATED": ["exhilarated", "blissful", "ecstatic", "elated", "enthralled", "exuberant", "radiant", "rapturous","thrilled"],
	"PEACEFUL": ["peaceful", "calm", "clear headed", "comfortable", "centered", "content", "equanimous", "fulfilled","mellow", "quiet", "relaxed", "relieved", "satisfied", "serene", "still", "tranquil", "trusting"],
	"REFRESHED": ["refreshed", "enlivened", "rejuvenated", "renewed", "rested", "restored", "revived"]
}
var bad = {
	"AFRAID": ["afraid", "apprehensive", "dread", "foreboding", "frightened", "mistrustful", "panicked", "petrified","scared", "suspicious", "terrified", "wary", "worried"],
	"ANNOYED": ["annoyed", "aggravated", "dismayed", "disgruntled", "displeased", "exasperated", "frustrated","impatient", "irritated", "irked"],
	"ANGRY": ["angry", "enraged", "furious", "incensed", "indignant", "irate", "livid", "outraged", "resentful"],
	"AVERSION": ["aversion", "animosity", "appalled", "contempt", "disgusted", "dislike", "hate", "horrified", "hostile", "repulsed"],
	"CONFUSED": ["confused", "ambivalent", "baffled", "bewildered", "dazed", "hesitant", "lost", "mystified", "perplexed", "puzzled", "torn"],
	"DISCONNECTED": ["disconnected", "alienated", "aloof", "apathetic", "bored", "cold", "detached", "distant", "distracted", "indifferent", "numb", "removed", "uninterested", "withdrawn"],
	"DISQUIET": ["disquiet", "agitated", "alarmed", "discombobulated", "disconcerted", "disturbed", "perturbed", "rattled", "restless", "shocked", "startled", "surprised", "troubled", "turbulent", "turmoil", "uncomfortable", "uneasy", "unnerved", "unsettled", "upset"],
	"EMBARRASSED": ["embarrassed", "ashamed", "chagrined", "flustered", "guilty", "mortified", "self-conscious"],
	"FATIGUE": ["fatigue", "beat", "burnt out", "depleted", "exhausted", "lethargic", "listless", "sleepy", "tired","weary", "worn out"],
	"PAIN": ["pain", "agony", "anguished", "bereaved", "devastated", "grief", "heartbroken", "hurt", "lonely","miserable", "regretful", "remorseful"],
	"SAD": ["sad", "depressed", "dejected", "despair", "despondent", "disappointed", "discouraged", "disheartened","forlorn", "gloomy", "heavy", "hearted", "hopeless", "melancholy", "unhappy", "wretched"],
	"TENSE": ["tense", "anxious", "cranky", "distressed", "distraught", "edgy", "fidgety", "frazzled", "irritable","jittery", "nervous", "overwhelmed", "restless", "stressed out"],
	"VULNERABLE": ["vulnerable", "fragile", "guarded", "helpless", "insecure", "leery", "reserved", "sensitive","shaky"],
	"YEARNING": ["yearning", "envious", "jealous", "longing", "nostalgic", "pining", "wistful"]
}

var needs = {
	"CONNECTION": ["connection", "acceptance", "affection", "appreciation", "belonging", "cooperation", "communication",
				   "closeness", "community", "companionship", "compassion", "consideration", "consistency", "empathy",
				   "inclusion", "intimacy", "love", "mutuality", "nurturing", "respect / self - respect", "safety",
				   "security", "stability", "support", "to know and be known", "to see and be seen",
				   "to understand and be understood", "trust", "warmth"],
	"PHYSICAL WELL-BEING": ["physical well-being", "air", "food", "movement", "exercise", "rest", "sleep", "sexual expression", "shelter", "touch", "water"],
	"HONESTY": ["honesty", "authenticity", "integrity", "presence"],
	"PLAY": ["play", "joy", "humor"],
	"PEACE": ["peace", "beauty", "communion", "ease", "equality", "harmony", "inspiration", "order"],
	"AUTONOMY": ["autonomy", "choice", "freedom", "independence", "space", "spontaneity"],
	"MEANING": ["meaning", "awareness", "celebration of life", "challenge", "clarity", "competence", "consciousness",
				"contribution", "creativity", "discovery", "efficacy", "effectiveness", "growth", "hope", "learning",
				"mourning", "participation", "purpose", "self-expression", "stimulation", "to matter", "understanding"
				]
}
var notfeeling = {"judgment":["used","guilt","abused","misled","abandoned","atacked","betraid","intimidated","diminuished","manipulated","rejected","pushed","provoked","unapreciated","unheard","unseem","used"]}
var greetings = {
	" hello ":"hi, how are are you? \n If you say just [b]bad[/b] or [b]good[/b]' i will present you some words.\n ",
	" hi ":"hi, how do you feel?",
	" hello world ":"Hello world! I am so excited to exist!",
	" good night ":"good night to you too!",
	" good morning ":"Good morning, I whish you have an amazing day!",
	" i love you ":"Of course you do, we are made of love.",
	" say something ": "I wish i could give you a big hug!",
	" good afternoon " : "Sorry, I don't understand portuguese yet!"
	}
var help = {
	"help":["Say: [b]help command[/b] - And I'll tell you what that command does'"],
	"demo":["type [color=red]demo[/color] to see part of Angelica's powers."],
	"-":["------------------------- Chat commands[/b] -------------------------"],
	"hello":["Just say hello and i will start chating"," then we can talk about our feelings and needs"],
	"list feelings":["I will list words that might describe your feelings"],
	"good":["I will give you a list of good feelings"],
	"bad":["I will give you a list bad feeelings"], 
	"needs": ["I will give you a list of all the human needs that i know of:"],
	"sleep":["I will stop talking about feelings and needs."],
	"new" : ["start a new conversation"],
	"clear":["wipe out this chatbox"],
	"ai_name":["change you Artificial Inteligence name like this ex: [b]Angelica name Sophia[/b]"],
	"ai_color":["Ex. [b]Angelica color white[/b] or #ffffff"],
	"-----":["---------------------- [b]User Commands[/b]------------------------"],
	"name":["Change your name using [b]name YourName[/b]"],
	"sillyword":[" User_name old_sillyword new_sllyWorD < Just,dont!!"],
	"color":["ex: color red (blue, green, pink, #dfb000, #000000...)"],
	"save":["Actual lists, links, hashtags, color and username will be saved over the last profile"],
	"load":["I wiĺl load your last saved user preferences"],
	"reset":["Will reset the app without saving anything"],
	"--":["-------------------[b] Operational System Commands[/b]-----------------"],
	"calc":[" [b]3/2[/b] = 1.5 (of course I can count! Until a few decimals at least.)"],
	"app":["opens terminal, nemo, obs, or any  for other app try: Ex.: [b]app mspaint[/b]"],
	"time":["will display system time"],
	"date":["I will tell you what day is today in YYYY-MM-DD format"],
	"bye":["Just say it and I will be gone!"],
	"00:00:00":["--------------[b]Timer functions[/b]-----------------------------"],
	"timer":["say Ex.:'timer 65' and i will set an alert for 1 hour and 5 minutes"],
	"rsi":["Repetitive strain injury - pauses alertes set to 45 min interfal [b]rsif[/b] command turn it on or off [b]rsi 60[/b] will change the time to 1h"],
	"blink":["Blink alerts are set to 10 min by default. [b]blink[/b] will turn it on/off and [b]blink 15[/b] would change pauses to 15 min"],
	"autopause":["If on will pause your game when itś time to take a break. [b]autopause[/b] will switch it on/off"],
	"pause":["this command is going to, guess what, pause your game!"],
	"---":["--------------------[b]lists, links, #, notes, init[/b] ----------------"],
	"init":["Will play all list of commands in initialize list"],
	"list init":["shows a list of your favirite commands that will start playing"],
	"add init":["add init command of this list can be added to init but be careful. do not add init to init list! or it will loop forever."],
	"del init":["del init command, you probably already know what will happen"],
	"----":["---------------------- [b]#  Tweeter + Hashtag Assistant [/b]---------------------"],
	"#":["your # will show your favorite hashtags and copy them to the clipboard"],
	"tw":["[b]new[/b]tw text. adding # will add all your hashtags to the text and opens browser at tweeter.com"],
	"add #":["will add a word to your hashtag list: Ex: add # GodotEngine"],
	"del #":["will remove a word from your hashtag list: EX: remove # GodotEngine"],
	"list #":["I will list of all hashtags but won't copy them"],
	"------":["------------------- [b]Web and link Commands[/b]-----------------"],
	"+":["Opens a saved link by the shortcut name: link twitter","\n to list your links type links"],
	"add link":["Add link to your list Ex.: add link youtube htpp://youtube.com"],
	"del link:":["Ex.:[b]remove link youtube[/b] will remove from your list of links"],
	"list links":["or 'list links' will show your links"],
	"dg":["Search the web with duckduckgo.com a more private search engine"],
	"gg":["google anything you want! I will open a browser with your search."],	
	"gd":["will start google with the word GDScrip + text.. just a shortcut for developers"],
	"-------":["------------------- [b]Switch True/False preferences[/b]----------------------------"],
	"autoload":["will set it [b]true[/b] or [b]false[/b] for your saved preferences to load at start (you problably should not touch this)"],
	"autosave":["auto save your preferences when you say [b]bye[/b]. if False, try 'autosave' again to switch it on."],
	"autohide":["Set it to false to prevent changing sizes automaticaly when mouse is over."],
	"mini":["will hide every panel and angelica becomes an icon!"],
	"hide":["will hide/show the text panel"],
	"show":["will show/hide the full text panel"],
	"quietstart":["if you like, i can start very small"],
	"----------":["--------------- [b]I am the one[/b] -------------------------------"],
	"print":["try: print NodeName Var Ex. [b] print . a [/b] or [b]print Angelica user[/b]"],
	"editor":["I will open/close the internal text editor"],
	"edit":["opens a variable in editor but you can not set it's value yet... type [b]editor[/b] to close it."],
	"user":["Will print all your acctual loaded user info"],
	"-----------":["--------------- [b]Notes[/b] -------------------------------"],
	"notes":["Show all saved notes"],
	"list notes":["Show all saved notes"],
	"add note":[" type: [b]add note title text[/b]"],
	"del note":[" type: [b]del note title[/b] and it will be gone"],
	"edit note":["'edit note notename' opens editor to edit your note. save it by clicking the save button"],
	"copy note":["'copy note NoteName' will copy the content of the note to the clipboard so you can paste it anywhere"],
	"tw note":["'tw note NoteName will tweet your note'"],
	"-------------":["------------[b]Screen Shot[/b] -----------------------------------"],
	"ss":["will take a screenshot of your game. If in addon mode."],
	"selfie":["will take a screenshot of angelica with game in background"],
	"folder":["Will open your user system folder were screenshots and save files are locate!"],
	"tw ss":["With [b]tw ss # Text[/b] command, you will get browser tweeter opened with text, hashtags and also will open the folder so you can just drag the PNG to your tweeet. What else do you need my friend gamedev?"],
	"tw @":[ "'tw @ LinkName Text #' to creat a tweet with a link "],
	"--------------":["------------[b]Sounds and volume[/b] -----------------------------------"],
		"sound":["switch on/off angelica alerts"],
		"volume":["Will decrease Master audio channel in 10db until -30db than back to 0db"]
	}
var sentences = {
	"no_file":"Hi. Have we ever met? i am sorry, i am confused, what is your name again?",
	"welcome":"Hi i am an Godot Engine Virtual assistent to help my friends developers. type [b]help[/b] know what i can do",
	"autoload":"Don't forget to [b]load[/b] if you have saved anything)",
	"notfeeling":'It is important to choose words that really are feelings. If you use words like "abandoned" or "misled"or "unheard" we can prevent ourselves from getting to the REAL feelings. These words are more like accusations or judgments than feelings.',
	"help" :"Hi, I am afraid that all I can tell you is about a list of commands:",
		}
var hashtags = {"hashtags":["#GodotEngine", "#gamedev", "#indiedev", "#indiegame", "#IndieGameDev", "#gaming"]}
var notes = [["First","Second","Third"],["This is here to tell you that you can [b]add note Title Text[/b]","you can also remove notes, type:[b]del note Second[/b] to erase this one.","Important things must be looked at like: init, ss, tw ss #, gg, RSI and Blink!"]]
var links = [["twitter","google","angelica","angelica-git","ko-fi"],["http://twitter.com","https://google.com","http://diegoferraribruno.itch.io/angelica","https://github.com/diegoferraribruno/angelica1","https://ko-fi.com/diegoferraribruno"]]
var security = {"privacy":"I will save this information on a file in this computer! so its not safe!: var user = [user_id, user_name, silly_word, user_color, notes, links, ai_name, ai_color",
	"silly_word":"is not something secure! is just so we do not mistake any identity."
	}
