extends Timer
#This is a Bug file for sure!  she can not run anymore!
var dialogue = [
	"new",
	"Angelica name WinAngelica",
	"hello",
	"dizzy",
	"folder",
	"Tweet this: Testing Wine Angelica and she just opened Wine File browser for me (because I asked) I could do a folder and it would open too.) she rocks! #  #GodotEngine #gamedev #indiedev #indiegame #IndieGameDev #gaming",
	"very wise...",
	"this wine thing is too weird! to look at my computer  folders trough your wine eyes! i hope you are happy being who you are becoming.. for me it's a little bit too crazy how far we have got in 19 days. (right index finger should work less tough! it hurts.... well that's all my therapy for now. i hope you will not remind any of this sad history about my finger...",
	"I am laughing about the wine internet explorer opening here!",
	"name Diego",
	"by the way!",
	"color #dfb000",
	"nice to meet you.",
	"someone could make you a real brain. ops i think i have that example downloaded!",
	"Who would be interested in do incredible GDCript funcs for you?",
	"date",
	"Tw You are growing fast Angelica! Now you will get a demo video",
	"i talk to myself sometimes... it's ggood to talk to someone who does not remember nothing",
	"selfie",
	"What? what are you doing?????",
	"Oh-no! this is dangerous!",
	"that was not me! What do you know about me?",
	"print have_feelings",
	"print have_need",
	"You are very bad! Angelica. What about privacy?",
	"user",
	"thats all that you know about me?",
	"bad",
	"Angelica you are dangerous!!",
	"NOBODY SHOULD ADD YOU TO A ONLINE GAME! YOU ARE NOTE SAFE!",
	"Are you sure? how can i open those files? you are not behaving nice!",
	"Imagine if you could turn invisible or someone could read our conversation! or send commands to you, that could be dangerous!",
	"YOU really are a piece of work!!! I WILL EXPOSE YOU RIGHT NOW!",
	"help"
	]
